javac GameComponents\RandomPlayer.java
javac GameComponents\HumanPlayer.java
javac GameComponents\AIPlayer.java
javac GameComponents\SeqPlayer.java
javac GameComponents\Player.java
javac GameComponents\BoardConfiguration.java
javac GameComponents\Checker.java
javac GameComponents\Move.java
javac GameComponents\MoveScore.java
javac GameComponents\ClientBoard.java
javac GameComponents\MNKBoard.java
javac GameComponents\Game.java
javac GameComponents\PlayerInfo.java
javac GameComponents\ResultsTable.java
javac GameComponents\PlacesTable.java
javac GameComponents\Tournament.java